### PR TITLE
Default export fix

### PR DESCRIPTION
**Pull request by aciccarello**
Fix for sebastian-lenz/typedoc#111

image

Renamed exports are still documented as their local name which might be unexpected.
image

I wasn't sure how to add tests for this change.

### CODE REVIEW

**Comment by sebastian-lenz** [comment]
Okay, lets do it like this. But we should somehow mark default exports.

**Comment by aciccarello** [comment]
@sebastian-lenz I agree. Maybe add a note to the end of the title. Like "Class SingleExportedClass (default)". I'd have to mess around and see how it looks.

**Comment by sebastian-lenz** [comment]
I'm planing to add an export table at the top of the documentations for external modules, seems to be the only reasonably way to show default exports and reexports.

**Comment by aciccarello** [comment]
Ah, I think that's a great idea. If love to see what you're thinking

**Pull request merged**
